packages:
  - apps/docs
  - apps/next-example
  - packages/config/eslint-custom
  - packages/config/tsconfig
  - packages/core
  - packages/next
  - packages/react
  - packages/providers/credentials
  - packages/providers/email
  - packages/sessions/cookie
  - packages/sessions/jwt
